grafana_admin_user: "{{ vault_grafana_admin_user }}"
grafana_admin_password: "{{ vault_grafana_admin_password }}"

prometheus_admin_user: "{{ vault_prometheus_admin_user }}"
prometheus_admin_password: "{{ vault_prometheus_admin_password }}"

