services:
  prometheus:
    image: prom/prometheus
    restart: "unless-stopped"
    volumes:
      - ./prometheus_config:/etc/prometheus/:ro
      - prometheus_data:/prometheus
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  prometheus_data:
networks:
  monitoring:
    external: true
