services:
  prometheus:
    image: prom/prometheus
    restart: "unless-stopped"
    volumes:
      - ./prometheus_config:/etc/prometheus/:ro
      - prometheus_data:/prometheus
    networks:
      - monitoring
volumes:
  prometheus_data:
networks:
  monitoring:
    external: true
