node_exporter_tls_server_config:
  cert_file: /etc/node_exporter/node_exporter.crt
  key_file: /etc/node_exporter/node_exporter.key

node_exporter_basic_auth_users: >-
  {{
    {
      node_exporter_admin_user: node_exporter_admin_password
    }
  }}
