- name: Generate selfsigned SSL certificate for monitoring server
  hosts: monitoring_servers
  become: true
  tasks:
    - name: Generate private key
      community.crypto.openssl_privatekey:
        path: "/etc/ssl/private/monitoring_server.key"
        size: "2048"
        type: RSA
  
    - name: Generate CSR
      community.crypto.openssl_csr:
        path: "/etc/ssl/private/monitoring_server.csr"
        privatekey_path: "/etc/ssl/private/monitoring_server.key"
        common_name: "{{ ansible_default_ipv4.address }}"
        subject_alt_name:
          - "IP:{{ ansible_default_ipv4.address }}"
    
    - name: Generate self-signed certificate
      community.crypto.x509_certificate:
        path: "/etc/ssl/certs/monitoring_server.crt"
        csr_path: "/etc/ssl/private/monitoring_server.csr"
        privatekey_path: "/etc/ssl/private/monitoring_server.key"
        provider: selfsigned
        selfsigned_not_after: "+365d"
        force: true

