- name: Configure Prometheus
  become: true
  become_user: "{{ os_user }}"
  block:
    - name: Ensure prometheus directory exists on host
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        owner: "{{ os_user }}"
        group: "{{ os_user }}"
        mode: "755"
      loop:
        - "/home/{{ os_user }}/prometheus"
        - "/home/{{ os_user }}/prometheus/prometheus_config"
    
    - name: Copy docker-compose.yml to host
      ansible.builtin.copy:
        src: "docker-compose.yml"
        dest: "/home/{{ os_user }}/prometheus/"
        owner: "{{ os_user }}"
        group: "{{ os_user }}"
        mode: "644"
    
    - name: Copy prometheus.yml to host from Jinja2 template
      ansible.builtin.template:
        src: "./prometheus.yml.j2"
        dest: "/home/{{ os_user }}/prometheus/prometheus_config/prometheus.yml"
        owner: "{{ os_user }}"
        group: "{{ os_user }}"
        mode: "644"
        
    
    - name: Run docker-compose.yml
      community.docker.docker_compose_v2:
        project_src: "/home/{{ os_user }}/prometheus/"
        files:
          - "docker-compose.yml"
        state: present
        recreate: always
