- name: Configure Nginx
  become: true
  become_user: "{{ os_user }}"
  block:
    - name: Ensure Nginx directory exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        owner: "{{ os_user }}"
        group: "{{ os_user }}"
        mode: "755"
      loop:
        - "/home/{{ os_user }}/nginx"
        - "/home/{{ os_user }}/nginx/nginx_conf"
    
    - name: Copy docker-compose.yml to host
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/home/{{ os_user }}/nginx/{{ item.dest }}"
        owner: "{{ os_user }}"
        group: "{{ os_user }}"
        mode: "644"
      loop:
        - { src: "docker-compose.yml", dest: "docker-compose.yml" }
        - { src: "prometheus.conf", dest: "nginx_conf/prometheus.conf" }
    
    - name: Create .htpasswd file for Nginx basic authentication
      ansible.builtin.template:
        src: ".htpasswd.j2"
        dest: "/home/{{ os_user }}/nginx/nginx_conf/.htpasswd"
        owner: "{{ os_user }}"
        group: "{{ os_user }}"
        mode: "644"
    
    - name: Run docker-compose.yml
      community.docker.docker_compose_v2:
        project_src: "/home/{{ os_user }}/nginx/"
        files:
          - "docker-compose.yml"
        state: present
        recreate: always
