all:
  vars:
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    app_servers:
      hosts:
        app_server:
          ansible_user: ansible
          ansible_host: 46.243.211.111
          os_user: app
    monitoring_servers:
      hosts:
        monitoring_server:
          ansible_user: ansible
          ansible_host: 111.88.149.245
          os_user: mon
