all:
  vars:
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    app_servers:
      hosts:
        app_server:
          ansible_user: ansible
          ansible_host: 158.160.12.217
          ansible_private_ip: 10.129.0.28
          os_user: app
    monitoring_servers:
      hosts:
        monitoring_server:
          ansible_user: ansible
          ansible_host: 111.88.153.23
          ansible_private_ip: 10.129.0.3
          os_user: mon
