all:
  vars:
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    app_servers:
      hosts:
        app_server:
          ansible_user: ansible
          ansible_host: 89.169.164.136
          os_user: app
    monitoring_servers:
      hosts:
        monitoring_server:
          ansible_user: ansible
          ansible_host: 37.230.168.77
          os_user: mon
