- name: Group-level fact gathering
  hosts: all
  tags:
    - always

- name: Setup hosts
  import_playbook: playbooks/setup-hosts.yml
  tags:
    - setup_hosts

- name: Install Docker
  import_playbook: playbooks/install-docker.yml
  tags: 
    - docker_install

- name: Deploy Docker Network
  import_playbook: playbooks/deploy-docker-network.yml
  tags:
    - docker_network_deploy

- name: Deploy Nginx
  import_playbook: playbooks/deploy-nginx.yml
  tags:
    - nginx_deploy 

- name: Deploy Prometheus
  import_playbook: playbooks/deploy-prometheus.yml
  tags:
    - prometheus_deploy

- name: Deploy node_exporter
  import_playbook: playbooks/deploy-node-exporter.yml
  tags:
    - node_exporter_deploy

- name: Deploy Grafana
  import_playbook: playbooks/deploy-grafana.yml
  tags:
    - grafana_deploy


